/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistrationWorkflows } from "./IRegistrationWorkflows";
export type { IRoyaltyWorkflows } from "./IRoyaltyWorkflows";
