/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace ISPGNFT {
  export type InitParamsStruct = {
    name: string;
    symbol: string;
    baseURI: string;
    contractURI: string;
    maxSupply: BigNumberish;
    mintFee: BigNumberish;
    mintFeeToken: AddressLike;
    mintFeeRecipient: AddressLike;
    owner: AddressLike;
    mintOpen: boolean;
    isPublicMinting: boolean;
  };

  export type InitParamsStructOutput = [
    name: string,
    symbol: string,
    baseURI: string,
    contractURI: string,
    maxSupply: bigint,
    mintFee: bigint,
    mintFeeToken: string,
    mintFeeRecipient: string,
    owner: string,
    mintOpen: boolean,
    isPublicMinting: boolean
  ] & {
    name: string;
    symbol: string;
    baseURI: string;
    contractURI: string;
    maxSupply: bigint;
    mintFee: bigint;
    mintFeeToken: string;
    mintFeeRecipient: string;
    owner: string;
    mintOpen: boolean;
    isPublicMinting: boolean;
  };
}

export declare namespace WorkflowStructs {
  export type IPMetadataStruct = {
    ipMetadataURI: string;
    ipMetadataHash: BytesLike;
    nftMetadataURI: string;
    nftMetadataHash: BytesLike;
  };

  export type IPMetadataStructOutput = [
    ipMetadataURI: string,
    ipMetadataHash: string,
    nftMetadataURI: string,
    nftMetadataHash: string
  ] & {
    ipMetadataURI: string;
    ipMetadataHash: string;
    nftMetadataURI: string;
    nftMetadataHash: string;
  };

  export type SignatureDataStruct = {
    signer: AddressLike;
    deadline: BigNumberish;
    signature: BytesLike;
  };

  export type SignatureDataStructOutput = [
    signer: string,
    deadline: bigint,
    signature: string
  ] & { signer: string; deadline: bigint; signature: string };
}

export interface IRegistrationWorkflowsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createCollection"
      | "mintAndRegisterIp"
      | "registerIp"
      | "setNftContractBeacon"
      | "upgradeCollections"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createCollection",
    values: [ISPGNFT.InitParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAndRegisterIp",
    values: [
      AddressLike,
      AddressLike,
      WorkflowStructs.IPMetadataStruct,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIp",
    values: [
      AddressLike,
      BigNumberish,
      WorkflowStructs.IPMetadataStruct,
      WorkflowStructs.SignatureDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftContractBeacon",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeCollections",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAndRegisterIp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registerIp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNftContractBeacon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeCollections",
    data: BytesLike
  ): Result;
}

export namespace CollectionCreatedEvent {
  export type InputTuple = [spgNftContract: AddressLike];
  export type OutputTuple = [spgNftContract: string];
  export interface OutputObject {
    spgNftContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRegistrationWorkflows extends BaseContract {
  connect(runner?: ContractRunner | null): IRegistrationWorkflows;
  waitForDeployment(): Promise<this>;

  interface: IRegistrationWorkflowsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCollection: TypedContractMethod<
    [spgNftInitParams: ISPGNFT.InitParamsStruct],
    [string],
    "nonpayable"
  >;

  mintAndRegisterIp: TypedContractMethod<
    [
      spgNftContract: AddressLike,
      recipient: AddressLike,
      ipMetadata: WorkflowStructs.IPMetadataStruct,
      allowDuplicates: boolean
    ],
    [[string, bigint] & { ipId: string; tokenId: bigint }],
    "nonpayable"
  >;

  registerIp: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      ipMetadata: WorkflowStructs.IPMetadataStruct,
      sigMetadata: WorkflowStructs.SignatureDataStruct
    ],
    [string],
    "nonpayable"
  >;

  setNftContractBeacon: TypedContractMethod<
    [newNftContractBeacon: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeCollections: TypedContractMethod<
    [newNftContract: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCollection"
  ): TypedContractMethod<
    [spgNftInitParams: ISPGNFT.InitParamsStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintAndRegisterIp"
  ): TypedContractMethod<
    [
      spgNftContract: AddressLike,
      recipient: AddressLike,
      ipMetadata: WorkflowStructs.IPMetadataStruct,
      allowDuplicates: boolean
    ],
    [[string, bigint] & { ipId: string; tokenId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerIp"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      ipMetadata: WorkflowStructs.IPMetadataStruct,
      sigMetadata: WorkflowStructs.SignatureDataStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNftContractBeacon"
  ): TypedContractMethod<
    [newNftContractBeacon: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeCollections"
  ): TypedContractMethod<[newNftContract: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CollectionCreated"
  ): TypedContractEvent<
    CollectionCreatedEvent.InputTuple,
    CollectionCreatedEvent.OutputTuple,
    CollectionCreatedEvent.OutputObject
  >;

  filters: {
    "CollectionCreated(address)": TypedContractEvent<
      CollectionCreatedEvent.InputTuple,
      CollectionCreatedEvent.OutputTuple,
      CollectionCreatedEvent.OutputObject
    >;
    CollectionCreated: TypedContractEvent<
      CollectionCreatedEvent.InputTuple,
      CollectionCreatedEvent.OutputTuple,
      CollectionCreatedEvent.OutputObject
    >;
  };
}
