/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace WorkflowStructs {
  export type ClaimRevenueDataStruct = {
    childIpId: AddressLike;
    royaltyPolicy: AddressLike;
    currencyToken: AddressLike;
  };

  export type ClaimRevenueDataStructOutput = [
    childIpId: string,
    royaltyPolicy: string,
    currencyToken: string
  ] & { childIpId: string; royaltyPolicy: string; currencyToken: string };
}

export interface IRoyaltyWorkflowsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimAllRevenue(address,address,(address,address,address)[])"
      | "claimAllRevenue(address,address,address[],address[],address[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimAllRevenue(address,address,(address,address,address)[])",
    values: [AddressLike, AddressLike, WorkflowStructs.ClaimRevenueDataStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllRevenue(address,address,address[],address[],address[])",
    values: [
      AddressLike,
      AddressLike,
      AddressLike[],
      AddressLike[],
      AddressLike[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimAllRevenue(address,address,(address,address,address)[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllRevenue(address,address,address[],address[],address[])",
    data: BytesLike
  ): Result;
}

export interface IRoyaltyWorkflows extends BaseContract {
  connect(runner?: ContractRunner | null): IRoyaltyWorkflows;
  waitForDeployment(): Promise<this>;

  interface: IRoyaltyWorkflowsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "claimAllRevenue(address,address,(address,address,address)[])": TypedContractMethod<
    [
      ancestorIpId: AddressLike,
      claimer: AddressLike,
      claimRevenueData: WorkflowStructs.ClaimRevenueDataStruct[]
    ],
    [bigint[]],
    "nonpayable"
  >;

  "claimAllRevenue(address,address,address[],address[],address[])": TypedContractMethod<
    [
      ancestorIpId: AddressLike,
      claimer: AddressLike,
      childIpIds: AddressLike[],
      royaltyPolicies: AddressLike[],
      currencyTokens: AddressLike[]
    ],
    [bigint[]],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimAllRevenue(address,address,(address,address,address)[])"
  ): TypedContractMethod<
    [
      ancestorIpId: AddressLike,
      claimer: AddressLike,
      claimRevenueData: WorkflowStructs.ClaimRevenueDataStruct[]
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimAllRevenue(address,address,address[],address[],address[])"
  ): TypedContractMethod<
    [
      ancestorIpId: AddressLike,
      claimer: AddressLike,
      childIpIds: AddressLike[],
      royaltyPolicies: AddressLike[],
      currencyTokens: AddressLike[]
    ],
    [bigint[]],
    "nonpayable"
  >;

  filters: {};
}
