module_name: "Event Sync"
version: "1.0.0"
description: "Backend event listeners that monitor blockchain events and synchronize database state"

dependencies:
  - blockchain_node
  - database_connection
  - event_queue
  - retry_mechanism

inputs:
  blockchain_events:
    type: "array"
    items:
      type: "object"
      properties:
        event_name:
          type: "string"
          enum: ["IPRegistered", "NFTMinted", "RoyaltyPaid", "LicenseGranted"]
        contract_address:
          type: "string"
          pattern: "^0x[a-fA-F0-9]{40}$"
        block_number:
          type: "number"
        transaction_hash:
          type: "string"
          pattern: "^0x[a-fA-F0-9]{64}$"
        log_index:
          type: "number"
        event_data:
          type: "object"
        timestamp:
          type: "string"
          format: "datetime"

outputs:
  database_updates:
    type: "object"
    properties:
      records_created:
        type: "number"
      records_updated:
        type: "number"
      records_failed:
        type: "number"
      last_processed_block:
        type: "number"
      processing_time:
        type: "number"
        description: "Time in milliseconds"
  
  sync_status:
    type: "object"
    properties:
      is_synced:
        type: "boolean"
      blocks_behind:
        type: "number"
      last_sync_time:
        type: "string"
        format: "datetime"
      error_count:
        type: "number"

workflow_steps:
  event_listener:
    1: "Connect to blockchain node WebSocket"
    2: "Subscribe to contract events"
    3: "Receive event notifications"
    4: "Parse event data"
    5: "Add to processing queue"
    6: "Acknowledge event receipt"
  
  event_processor:
    1: "Dequeue event from processing queue"
    2: "Validate event data structure"
    3: "Check if event already processed"
    4: "Transform event data for database"
    5: "Execute database transaction"
    6: "Update processing status"
    7: "Handle success/failure"
    8: "Update last processed block"
  
  sync_monitor:
    1: "Check current blockchain height"
    2: "Compare with last processed block"
    3: "Calculate sync lag"
    4: "Monitor processing queue size"
    5: "Alert on sync issues"
    6: "Generate sync status report"

backend_handling:
  event_listeners:
    - contract: "StoryProtocolCore"
      events:
        - "IPRegistered"
        - "NFTMinted"
      handler: "handleIPCreation"
    
    - contract: "RoyaltyModule"
      events:
        - "RoyaltyPaid"
      handler: "handleRoyaltyPayment"
    
    - contract: "LicensingModule"
      events:
        - "LicenseGranted"
      handler: "handleLicenseGrant"
  
  database_operations:
    - table: "nft_ips"
      operations: ["INSERT", "UPDATE"]
    - table: "royalty_payments"
      operations: ["INSERT"]
    - table: "licenses"
      operations: ["INSERT"]
    - table: "event_logs"
      operations: ["INSERT"]
  
  retry_mechanism:
    max_retries: 3
    backoff_strategy: "exponential"
    base_delay: 1000
    max_delay: 30000
    retry_conditions:
      - "database_connection_error"
      - "temporary_network_error"
      - "rate_limit_exceeded"

example_data_structures:
  ip_registered_event:
    event_name: "IPRegistered"
    contract_address: "0x1234567890123456789012345678901234567890"
    block_number: 18500000
    transaction_hash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
    log_index: 0
    event_data:
      ipId: "0xabcdef1234567890abcdef1234567890abcdef12"
      owner: "0x742d35Cc6634C0532925a3b8D4C9db96590c6C87"
      metadataURI: "ipfs://QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG"
      royaltyPercentage: 750  # 7.5% in basis points
    timestamp: "2024-01-15T10:30:00Z"
  
  nft_minted_event:
    event_name: "NFTMinted"
    contract_address: "0x1234567890123456789012345678901234567890"
    block_number: 18500000
    transaction_hash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
    log_index: 1
    event_data:
      tokenId: "1"
      to: "0x742d35Cc6634C0532925a3b8D4C9db96590c6C87"
      tokenURI: "ipfs://QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG"
    timestamp: "2024-01-15T10:30:00Z"
  
  royalty_paid_event:
    event_name: "RoyaltyPaid"
    contract_address: "0x2345678901234567890123456789012345678901"
    block_number: 18500100
    transaction_hash: "0xfedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321"
    log_index: 0
    event_data:
      ipId: "0xabcdef1234567890abcdef1234567890abcdef12"
      recipient: "0x742d35Cc6634C0532925a3b8D4C9db96590c6C87"
      amount: "50000000000000000"  # 0.05 ETH in wei
      currency: "0x0000000000000000000000000000000000000000"  # ETH
    timestamp: "2024-01-15T11:45:00Z"

database_schema_updates:
  nft_ips_table:
    operation: "INSERT"
    data_mapping:
      nft_id: "event_data.tokenId"
      ip_id: "event_data.ipId"
      metadata_uri: "event_data.metadataURI"
      creator_wallet: "event_data.owner"
      transaction_hash: "transaction_hash"
      block_number: "block_number"
      created_at: "timestamp"
  
  royalty_payments_table:
    operation: "INSERT"
    data_mapping:
      ip_id: "event_data.ipId"
      recipient: "event_data.recipient"
      amount: "event_data.amount"
      currency: "event_data.currency"
      transaction_hash: "transaction_hash"
      block_number: "block_number"
      paid_at: "timestamp"
  
  event_logs_table:
    operation: "INSERT"
    data_mapping:
      event_type: "event_name"
      contract_address: "contract_address"
      transaction_hash: "transaction_hash"
      block_number: "block_number"
      log_index: "log_index"
      processed_at: "current_timestamp"
      status: "processed"

monitoring_and_alerting:
  metrics:
    - name: "events_processed_per_minute"
      type: "counter"
    - name: "sync_lag_blocks"
      type: "gauge"
    - name: "processing_errors"
      type: "counter"
    - name: "queue_size"
      type: "gauge"
  
  alerts:
    - condition: "sync_lag_blocks > 100"
      severity: "warning"
      message: "Event sync is falling behind"
    
    - condition: "processing_errors > 10 in 5 minutes"
      severity: "critical"
      message: "High error rate in event processing"
    
    - condition: "queue_size > 1000"
      severity: "warning"
      message: "Event processing queue is backing up"

error_handling:
  duplicate_events:
    strategy: "ignore"
    detection: "transaction_hash + log_index uniqueness"
  
  malformed_events:
    strategy: "log_and_skip"
    logging_level: "error"
  
  database_errors:
    strategy: "retry_with_backoff"
    max_retries: 3
    dead_letter_queue: true
  
  network_errors:
    strategy: "reconnect_and_resume"
    reconnect_delay: 5000
    max_reconnect_attempts: 10

performance_optimization:
  batch_processing:
    enabled: true
    batch_size: 100
    max_wait_time: 5000
  
  connection_pooling:
    database_pool_size: 10
    websocket_connections: 3
  
  caching:
    processed_events_cache: true
    cache_ttl: 3600
    cache_size: 10000

data_consistency:
  transaction_isolation: "READ_COMMITTED"
  atomic_operations: true
  rollback_on_failure: true
  consistency_checks:
    - "verify_event_order"
    - "validate_data_integrity"
    - "check_foreign_key_constraints"

recovery_procedures:
  missed_events:
    detection: "block_gap_analysis"
    recovery: "historical_event_fetch"
    backfill_strategy: "chronological_order"
  
  corrupted_data:
    detection: "data_validation_checks"
    recovery: "reprocess_from_blockchain"
    verification: "cross_reference_with_node"
  
  service_restart:
    resume_from: "last_processed_block"
    state_persistence: "database_checkpoint"
    graceful_shutdown: true