/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistrationWorkflows__factory } from "./IRegistrationWorkflows__factory";
export { IRoyaltyWorkflows__factory } from "./IRoyaltyWorkflows__factory";
