/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRegistrationWorkflows,
  IRegistrationWorkflowsInterface,
} from "../../../../../../@storyprotocol/periphery/contracts/interfaces/workflows/IRegistrationWorkflows";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "spgNftContract",
        type: "address",
      },
    ],
    name: "CollectionCreated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "string",
            name: "baseURI",
            type: "string",
          },
          {
            internalType: "string",
            name: "contractURI",
            type: "string",
          },
          {
            internalType: "uint32",
            name: "maxSupply",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "mintFee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "mintFeeToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "mintFeeRecipient",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "bool",
            name: "mintOpen",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isPublicMinting",
            type: "bool",
          },
        ],
        internalType: "struct ISPGNFT.InitParams",
        name: "spgNftInitParams",
        type: "tuple",
      },
    ],
    name: "createCollection",
    outputs: [
      {
        internalType: "address",
        name: "spgNftContract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spgNftContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        components: [
          {
            internalType: "string",
            name: "ipMetadataURI",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "ipMetadataHash",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "nftMetadataURI",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "nftMetadataHash",
            type: "bytes32",
          },
        ],
        internalType: "struct WorkflowStructs.IPMetadata",
        name: "ipMetadata",
        type: "tuple",
      },
      {
        internalType: "bool",
        name: "allowDuplicates",
        type: "bool",
      },
    ],
    name: "mintAndRegisterIp",
    outputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nftContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "ipMetadataURI",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "ipMetadataHash",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "nftMetadataURI",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "nftMetadataHash",
            type: "bytes32",
          },
        ],
        internalType: "struct WorkflowStructs.IPMetadata",
        name: "ipMetadata",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "signer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct WorkflowStructs.SignatureData",
        name: "sigMetadata",
        type: "tuple",
      },
    ],
    name: "registerIp",
    outputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newNftContractBeacon",
        type: "address",
      },
    ],
    name: "setNftContractBeacon",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newNftContract",
        type: "address",
      },
    ],
    name: "upgradeCollections",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRegistrationWorkflows__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistrationWorkflowsInterface {
    return new Interface(_abi) as IRegistrationWorkflowsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRegistrationWorkflows {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRegistrationWorkflows;
  }
}
