/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoyaltyWorkflows,
  IRoyaltyWorkflowsInterface,
} from "../../../../../../@storyprotocol/periphery/contracts/interfaces/workflows/IRoyaltyWorkflows";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "ancestorIpId",
        type: "address",
      },
      {
        internalType: "address",
        name: "claimer",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "childIpId",
            type: "address",
          },
          {
            internalType: "address",
            name: "royaltyPolicy",
            type: "address",
          },
          {
            internalType: "address",
            name: "currencyToken",
            type: "address",
          },
        ],
        internalType: "struct WorkflowStructs.ClaimRevenueData[]",
        name: "claimRevenueData",
        type: "tuple[]",
      },
    ],
    name: "claimAllRevenue",
    outputs: [
      {
        internalType: "uint256[]",
        name: "amountsClaimed",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ancestorIpId",
        type: "address",
      },
      {
        internalType: "address",
        name: "claimer",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "childIpIds",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "royaltyPolicies",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "currencyTokens",
        type: "address[]",
      },
    ],
    name: "claimAllRevenue",
    outputs: [
      {
        internalType: "uint256[]",
        name: "amountsClaimed",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRoyaltyWorkflows__factory {
  static readonly abi = _abi;
  static createInterface(): IRoyaltyWorkflowsInterface {
    return new Interface(_abi) as IRoyaltyWorkflowsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoyaltyWorkflows {
    return new Contract(address, _abi, runner) as unknown as IRoyaltyWorkflows;
  }
}
