/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export * as licensing from "./licensing";
export * as royalty from "./royalty";
