import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import MockDataIndicator from "@/components/MockDataIndicator";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Klaim | Decentralized IP store</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="data-theme" defaultTheme="light">
          <Navbar />
          {children}
          <MockDataIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
