import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import "./globals.css";

// Geist font family configuration for modern typography
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Application metadata for SEO and browser display
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout Component for Application Structure
 * 
 * This component defines the fundamental HTML structure and layout for the
 * entire application including font configuration, global styling, provider
 * setup, and navigation integration. It ensures consistent layout structure
 * across all pages while providing the necessary context providers and
 * navigation components for a seamless user experience throughout the platform.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Klaim | Decentralized IP store</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
