/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DerivativeManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "IP_ASSET_REGISTRY"
      | "LICENSE_REGISTRY"
      | "LICENSING_MODULE"
      | "getDerivativeIp"
      | "getDerivativeIpCount"
      | "getParentIp"
      | "getParentIpCount"
      | "hasDerivativeIps"
      | "isDerivativeIp"
      | "isParentIp"
      | "registerDerivativeWithLicenseTokens"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DerivativeRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "IP_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDerivativeIp",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDerivativeIpCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParentIp",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParentIpCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDerivativeIps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDerivativeIp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isParentIp",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDerivativeWithLicenseTokens",
    values: [AddressLike, BigNumberish[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "IP_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDerivativeIp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDerivativeIpCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParentIp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParentIpCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasDerivativeIps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDerivativeIp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isParentIp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDerivativeWithLicenseTokens",
    data: BytesLike
  ): Result;
}

export namespace DerivativeRegisteredEvent {
  export type InputTuple = [
    childIpId: AddressLike,
    parentIpId: AddressLike,
    licenseTokenIds: BigNumberish[]
  ];
  export type OutputTuple = [
    childIpId: string,
    parentIpId: string,
    licenseTokenIds: bigint[]
  ];
  export interface OutputObject {
    childIpId: string;
    parentIpId: string;
    licenseTokenIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DerivativeManager extends BaseContract {
  connect(runner?: ContractRunner | null): DerivativeManager;
  waitForDeployment(): Promise<this>;

  interface: DerivativeManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IP_ASSET_REGISTRY: TypedContractMethod<[], [string], "view">;

  LICENSE_REGISTRY: TypedContractMethod<[], [string], "view">;

  LICENSING_MODULE: TypedContractMethod<[], [string], "view">;

  getDerivativeIp: TypedContractMethod<
    [parentIpId: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getDerivativeIpCount: TypedContractMethod<
    [parentIpId: AddressLike],
    [bigint],
    "view"
  >;

  getParentIp: TypedContractMethod<
    [childIpId: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getParentIpCount: TypedContractMethod<
    [childIpId: AddressLike],
    [bigint],
    "view"
  >;

  hasDerivativeIps: TypedContractMethod<[ipId: AddressLike], [boolean], "view">;

  isDerivativeIp: TypedContractMethod<[ipId: AddressLike], [boolean], "view">;

  isParentIp: TypedContractMethod<
    [parentIpId: AddressLike, childIpId: AddressLike],
    [boolean],
    "view"
  >;

  registerDerivativeWithLicenseTokens: TypedContractMethod<
    [
      childIpId: AddressLike,
      licenseTokenIds: BigNumberish[],
      maxRts: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IP_ASSET_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSE_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDerivativeIp"
  ): TypedContractMethod<
    [parentIpId: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDerivativeIpCount"
  ): TypedContractMethod<[parentIpId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParentIp"
  ): TypedContractMethod<
    [childIpId: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParentIpCount"
  ): TypedContractMethod<[childIpId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasDerivativeIps"
  ): TypedContractMethod<[ipId: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDerivativeIp"
  ): TypedContractMethod<[ipId: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isParentIp"
  ): TypedContractMethod<
    [parentIpId: AddressLike, childIpId: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerDerivativeWithLicenseTokens"
  ): TypedContractMethod<
    [
      childIpId: AddressLike,
      licenseTokenIds: BigNumberish[],
      maxRts: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DerivativeRegistered"
  ): TypedContractEvent<
    DerivativeRegisteredEvent.InputTuple,
    DerivativeRegisteredEvent.OutputTuple,
    DerivativeRegisteredEvent.OutputObject
  >;

  filters: {
    "DerivativeRegistered(address,address,uint256[])": TypedContractEvent<
      DerivativeRegisteredEvent.InputTuple,
      DerivativeRegisteredEvent.OutputTuple,
      DerivativeRegisteredEvent.OutputObject
    >;
    DerivativeRegistered: TypedContractEvent<
      DerivativeRegisteredEvent.InputTuple,
      DerivativeRegisteredEvent.OutputTuple,
      DerivativeRegisteredEvent.OutputObject
    >;
  };
}
