/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ExampleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "IP_ASSET_REGISTRY"
      | "LICENSING_MODULE"
      | "PIL_TEMPLATE"
      | "ROYALTY_POLICY_LAP"
      | "SIMPLE_NFT"
      | "WIP"
      | "mintAndRegisterAndCreateTermsAndAttach"
      | "mintLicenseTokenAndRegisterDerivative"
      | "onERC721Received"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "IP_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_POLICY_LAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIMPLE_NFT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WIP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintAndRegisterAndCreateTermsAndAttach",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintLicenseTokenAndRegisterDerivative",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IP_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_POLICY_LAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SIMPLE_NFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WIP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintAndRegisterAndCreateTermsAndAttach",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintLicenseTokenAndRegisterDerivative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
}

export interface Example extends BaseContract {
  connect(runner?: ContractRunner | null): Example;
  waitForDeployment(): Promise<this>;

  interface: ExampleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IP_ASSET_REGISTRY: TypedContractMethod<[], [string], "view">;

  LICENSING_MODULE: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  ROYALTY_POLICY_LAP: TypedContractMethod<[], [string], "view">;

  SIMPLE_NFT: TypedContractMethod<[], [string], "view">;

  WIP: TypedContractMethod<[], [string], "view">;

  mintAndRegisterAndCreateTermsAndAttach: TypedContractMethod<
    [receiver: AddressLike],
    [
      [bigint, string, bigint] & {
        tokenId: bigint;
        ipId: string;
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;

  mintLicenseTokenAndRegisterDerivative: TypedContractMethod<
    [
      parentIpId: AddressLike,
      licenseTermsId: BigNumberish,
      receiver: AddressLike
    ],
    [[bigint, string] & { childTokenId: bigint; childIpId: string }],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IP_ASSET_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_POLICY_LAP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SIMPLE_NFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WIP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintAndRegisterAndCreateTermsAndAttach"
  ): TypedContractMethod<
    [receiver: AddressLike],
    [
      [bigint, string, bigint] & {
        tokenId: bigint;
        ipId: string;
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintLicenseTokenAndRegisterDerivative"
  ): TypedContractMethod<
    [
      parentIpId: AddressLike,
      licenseTermsId: BigNumberish,
      receiver: AddressLike
    ],
    [[bigint, string] & { childTokenId: bigint; childIpId: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
