/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { DerivativeManager } from "./DerivativeManager";
export type { Example } from "./Example";
export type { IPARegistrar } from "./IPARegistrar";
export type { IPAccountManager } from "./IPAccountManager";
export type { IPCreator } from "./IPCreator";
export type { IPMarketplace } from "./IPMarketplace";
export type { IPToken } from "./IPToken";
export type { LicenseAttacher } from "./LicenseAttacher";
export type { LicenseTermsManager } from "./LicenseTermsManager";
export type { LicenseTokenManager } from "./LicenseTokenManager";
export type { LicenseViewer } from "./LicenseViewer";
export type { RoyaltyManager } from "./RoyaltyManager";
export type { StoryProtocolGateway } from "./StoryProtocolGateway";
