/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WorkflowStructs {
  export type IPMetadataStruct = {
    ipMetadataURI: string;
    ipMetadataHash: BytesLike;
    nftMetadataURI: string;
    nftMetadataHash: BytesLike;
  };

  export type IPMetadataStructOutput = [
    ipMetadataURI: string,
    ipMetadataHash: string,
    nftMetadataURI: string,
    nftMetadataHash: string
  ] & {
    ipMetadataURI: string;
    ipMetadataHash: string;
    nftMetadataURI: string;
    nftMetadataHash: string;
  };
}

export interface IPARegistrarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "IP_ASSET_REGISTRY"
      | "REGISTRATION_WORKFLOWS"
      | "mintAndRegisterIp"
      | "owner"
      | "register"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IPMintedAndRegistered"
      | "IPRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "IP_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRATION_WORKFLOWS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAndRegisterIp",
    values: [
      AddressLike,
      AddressLike,
      WorkflowStructs.IPMetadataStruct,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IP_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRATION_WORKFLOWS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAndRegisterIp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace IPMintedAndRegisteredEvent {
  export type InputTuple = [
    ipId: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    ipId: string,
    nftContract: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    ipId: string;
    nftContract: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IPRegisteredEvent {
  export type InputTuple = [
    ipId: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    ipId: string,
    nftContract: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    ipId: string;
    nftContract: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPARegistrar extends BaseContract {
  connect(runner?: ContractRunner | null): IPARegistrar;
  waitForDeployment(): Promise<this>;

  interface: IPARegistrarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IP_ASSET_REGISTRY: TypedContractMethod<[], [string], "view">;

  REGISTRATION_WORKFLOWS: TypedContractMethod<[], [string], "view">;

  mintAndRegisterIp: TypedContractMethod<
    [
      _spgNftContract: AddressLike,
      _recipient: AddressLike,
      _metadata: WorkflowStructs.IPMetadataStruct,
      _bindIpToNft: boolean
    ],
    [[string, bigint] & { ipId: string; tokenId: bigint }],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<
    [_nftContract: AddressLike, _tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IP_ASSET_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGISTRATION_WORKFLOWS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintAndRegisterIp"
  ): TypedContractMethod<
    [
      _spgNftContract: AddressLike,
      _recipient: AddressLike,
      _metadata: WorkflowStructs.IPMetadataStruct,
      _bindIpToNft: boolean
    ],
    [[string, bigint] & { ipId: string; tokenId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [_nftContract: AddressLike, _tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "IPMintedAndRegistered"
  ): TypedContractEvent<
    IPMintedAndRegisteredEvent.InputTuple,
    IPMintedAndRegisteredEvent.OutputTuple,
    IPMintedAndRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IPRegistered"
  ): TypedContractEvent<
    IPRegisteredEvent.InputTuple,
    IPRegisteredEvent.OutputTuple,
    IPRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "IPMintedAndRegistered(address,address,uint256)": TypedContractEvent<
      IPMintedAndRegisteredEvent.InputTuple,
      IPMintedAndRegisteredEvent.OutputTuple,
      IPMintedAndRegisteredEvent.OutputObject
    >;
    IPMintedAndRegistered: TypedContractEvent<
      IPMintedAndRegisteredEvent.InputTuple,
      IPMintedAndRegisteredEvent.OutputTuple,
      IPMintedAndRegisteredEvent.OutputObject
    >;

    "IPRegistered(address,address,uint256)": TypedContractEvent<
      IPRegisteredEvent.InputTuple,
      IPRegisteredEvent.OutputTuple,
      IPRegisteredEvent.OutputObject
    >;
    IPRegistered: TypedContractEvent<
      IPRegisteredEvent.InputTuple,
      IPRegisteredEvent.OutputTuple,
      IPRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
