/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPCreatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "IP_ASSET_REGISTRY"
      | "LICENSING_MODULE"
      | "MERC20"
      | "NFT_CONTRACT"
      | "PIL_TEMPLATE"
      | "ROYALTY_POLICY_LAP"
      | "batchCreateIPs"
      | "createIPFromFile"
      | "getNFTContract"
      | "onERC721Received"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IPAssetCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "IP_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MERC20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "NFT_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_POLICY_LAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchCreateIPs",
    values: [AddressLike[], string[], BytesLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "createIPFromFile",
    values: [AddressLike, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNFTContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IP_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NFT_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_POLICY_LAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCreateIPs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIPFromFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
}

export namespace IPAssetCreatedEvent {
  export type InputTuple = [
    ipId: AddressLike,
    tokenId: BigNumberish,
    owner: AddressLike,
    metadataURI: string,
    licenseTermsId: BigNumberish
  ];
  export type OutputTuple = [
    ipId: string,
    tokenId: bigint,
    owner: string,
    metadataURI: string,
    licenseTermsId: bigint
  ];
  export interface OutputObject {
    ipId: string;
    tokenId: bigint;
    owner: string;
    metadataURI: string;
    licenseTermsId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPCreator extends BaseContract {
  connect(runner?: ContractRunner | null): IPCreator;
  waitForDeployment(): Promise<this>;

  interface: IPCreatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IP_ASSET_REGISTRY: TypedContractMethod<[], [string], "view">;

  LICENSING_MODULE: TypedContractMethod<[], [string], "view">;

  MERC20: TypedContractMethod<[], [string], "view">;

  NFT_CONTRACT: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  ROYALTY_POLICY_LAP: TypedContractMethod<[], [string], "view">;

  batchCreateIPs: TypedContractMethod<
    [
      recipients: AddressLike[],
      metadataURIs: string[],
      metadataHashes: BytesLike[],
      licenseURI: string
    ],
    [
      [bigint[], string[], bigint] & {
        tokenIds: bigint[];
        ipIds: string[];
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;

  createIPFromFile: TypedContractMethod<
    [
      recipient: AddressLike,
      metadataURI: string,
      metadataHash: BytesLike,
      licenseURI: string
    ],
    [
      [bigint, string, bigint] & {
        tokenId: bigint;
        ipId: string;
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;

  getNFTContract: TypedContractMethod<[], [string], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IP_ASSET_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MERC20"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NFT_CONTRACT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_POLICY_LAP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchCreateIPs"
  ): TypedContractMethod<
    [
      recipients: AddressLike[],
      metadataURIs: string[],
      metadataHashes: BytesLike[],
      licenseURI: string
    ],
    [
      [bigint[], string[], bigint] & {
        tokenIds: bigint[];
        ipIds: string[];
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIPFromFile"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      metadataURI: string,
      metadataHash: BytesLike,
      licenseURI: string
    ],
    [
      [bigint, string, bigint] & {
        tokenId: bigint;
        ipId: string;
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNFTContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "IPAssetCreated"
  ): TypedContractEvent<
    IPAssetCreatedEvent.InputTuple,
    IPAssetCreatedEvent.OutputTuple,
    IPAssetCreatedEvent.OutputObject
  >;

  filters: {
    "IPAssetCreated(address,uint256,address,string,uint256)": TypedContractEvent<
      IPAssetCreatedEvent.InputTuple,
      IPAssetCreatedEvent.OutputTuple,
      IPAssetCreatedEvent.OutputObject
    >;
    IPAssetCreated: TypedContractEvent<
      IPAssetCreatedEvent.InputTuple,
      IPAssetCreatedEvent.OutputTuple,
      IPAssetCreatedEvent.OutputObject
    >;
  };
}
