/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "IP_ASSET_REGISTRY"
      | "IP_TOKEN"
      | "NFT_CONTRACT"
      | "cancelListing"
      | "listIP"
      | "listings"
      | "purchaseIP"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "IPListed" | "IPSold" | "ListingCancelled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "IP_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "IP_TOKEN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "NFT_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listIP",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "listings", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "purchaseIP",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IP_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "IP_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NFT_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listIP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "purchaseIP", data: BytesLike): Result;
}

export namespace IPListedEvent {
  export type InputTuple = [
    listingId: BytesLike,
    seller: AddressLike,
    ipId: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    listingId: string,
    seller: string,
    ipId: string,
    price: bigint
  ];
  export interface OutputObject {
    listingId: string;
    seller: string;
    ipId: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IPSoldEvent {
  export type InputTuple = [
    listingId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    ipId: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    listingId: string,
    buyer: string,
    seller: string,
    ipId: string,
    price: bigint
  ];
  export interface OutputObject {
    listingId: string;
    buyer: string;
    seller: string;
    ipId: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BytesLike];
  export type OutputTuple = [listingId: string];
  export interface OutputObject {
    listingId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): IPMarketplace;
  waitForDeployment(): Promise<this>;

  interface: IPMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IP_ASSET_REGISTRY: TypedContractMethod<[], [string], "view">;

  IP_TOKEN: TypedContractMethod<[], [string], "view">;

  NFT_CONTRACT: TypedContractMethod<[], [string], "view">;

  cancelListing: TypedContractMethod<
    [listingId: BytesLike],
    [void],
    "nonpayable"
  >;

  listIP: TypedContractMethod<
    [tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, bigint, boolean] & {
        seller: string;
        tokenId: bigint;
        ipId: string;
        price: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  purchaseIP: TypedContractMethod<[listingId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IP_ASSET_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IP_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NFT_CONTRACT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listIP"
  ): TypedContractMethod<
    [tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, bigint, boolean] & {
        seller: string;
        tokenId: bigint;
        ipId: string;
        price: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseIP"
  ): TypedContractMethod<[listingId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "IPListed"
  ): TypedContractEvent<
    IPListedEvent.InputTuple,
    IPListedEvent.OutputTuple,
    IPListedEvent.OutputObject
  >;
  getEvent(
    key: "IPSold"
  ): TypedContractEvent<
    IPSoldEvent.InputTuple,
    IPSoldEvent.OutputTuple,
    IPSoldEvent.OutputObject
  >;
  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;

  filters: {
    "IPListed(bytes32,address,address,uint256)": TypedContractEvent<
      IPListedEvent.InputTuple,
      IPListedEvent.OutputTuple,
      IPListedEvent.OutputObject
    >;
    IPListed: TypedContractEvent<
      IPListedEvent.InputTuple,
      IPListedEvent.OutputTuple,
      IPListedEvent.OutputObject
    >;

    "IPSold(bytes32,address,address,address,uint256)": TypedContractEvent<
      IPSoldEvent.InputTuple,
      IPSoldEvent.OutputTuple,
      IPSoldEvent.OutputObject
    >;
    IPSold: TypedContractEvent<
      IPSoldEvent.InputTuple,
      IPSoldEvent.OutputTuple,
      IPSoldEvent.OutputObject
    >;

    "ListingCancelled(bytes32)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
  };
}
