/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LicenseAttacherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LICENSE_REGISTRY"
      | "LICENSING_MODULE"
      | "PIL_TEMPLATE"
      | "attachLicenseTerms"
      | "getAttachedLicenseTerms"
      | "getAttachedLicenseTermsCount"
      | "hasAttachedLicenseTerms"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LicenseTermsAttached"): EventFragment;

  encodeFunctionData(
    functionFragment: "LICENSE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attachLicenseTerms",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttachedLicenseTerms",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttachedLicenseTermsCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAttachedLicenseTerms",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LICENSE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attachLicenseTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttachedLicenseTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttachedLicenseTermsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAttachedLicenseTerms",
    data: BytesLike
  ): Result;
}

export namespace LicenseTermsAttachedEvent {
  export type InputTuple = [
    ipId: AddressLike,
    licenseTemplate: AddressLike,
    licenseTermsId: BigNumberish
  ];
  export type OutputTuple = [
    ipId: string,
    licenseTemplate: string,
    licenseTermsId: bigint
  ];
  export interface OutputObject {
    ipId: string;
    licenseTemplate: string;
    licenseTermsId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LicenseAttacher extends BaseContract {
  connect(runner?: ContractRunner | null): LicenseAttacher;
  waitForDeployment(): Promise<this>;

  interface: LicenseAttacherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LICENSE_REGISTRY: TypedContractMethod<[], [string], "view">;

  LICENSING_MODULE: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  attachLicenseTerms: TypedContractMethod<
    [ipId: AddressLike, licenseTermsId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAttachedLicenseTerms: TypedContractMethod<
    [ipId: AddressLike, index: BigNumberish],
    [[string, bigint] & { licenseTemplate: string; licenseTermsId: bigint }],
    "view"
  >;

  getAttachedLicenseTermsCount: TypedContractMethod<
    [ipId: AddressLike],
    [bigint],
    "view"
  >;

  hasAttachedLicenseTerms: TypedContractMethod<
    [ipId: AddressLike, licenseTermsId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LICENSE_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attachLicenseTerms"
  ): TypedContractMethod<
    [ipId: AddressLike, licenseTermsId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttachedLicenseTerms"
  ): TypedContractMethod<
    [ipId: AddressLike, index: BigNumberish],
    [[string, bigint] & { licenseTemplate: string; licenseTermsId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttachedLicenseTermsCount"
  ): TypedContractMethod<[ipId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasAttachedLicenseTerms"
  ): TypedContractMethod<
    [ipId: AddressLike, licenseTermsId: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "LicenseTermsAttached"
  ): TypedContractEvent<
    LicenseTermsAttachedEvent.InputTuple,
    LicenseTermsAttachedEvent.OutputTuple,
    LicenseTermsAttachedEvent.OutputObject
  >;

  filters: {
    "LicenseTermsAttached(address,address,uint256)": TypedContractEvent<
      LicenseTermsAttachedEvent.InputTuple,
      LicenseTermsAttachedEvent.OutputTuple,
      LicenseTermsAttachedEvent.OutputObject
    >;
    LicenseTermsAttached: TypedContractEvent<
      LicenseTermsAttachedEvent.InputTuple,
      LicenseTermsAttachedEvent.OutputTuple,
      LicenseTermsAttachedEvent.OutputObject
    >;
  };
}
