/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type LicenseDataStruct = {
  licenseTemplate: AddressLike;
  licenseTermsId: BigNumberish;
  licenseURI: string;
  commercialUse: boolean;
  derivativesAllowed: boolean;
  commercialRevShare: BigNumberish;
  mintingFee: BigNumberish;
  currency: AddressLike;
};

export type LicenseDataStructOutput = [
  licenseTemplate: string,
  licenseTermsId: bigint,
  licenseURI: string,
  commercialUse: boolean,
  derivativesAllowed: boolean,
  commercialRevShare: bigint,
  mintingFee: bigint,
  currency: string
] & {
  licenseTemplate: string;
  licenseTermsId: bigint;
  licenseURI: string;
  commercialUse: boolean;
  derivativesAllowed: boolean;
  commercialRevShare: bigint;
  mintingFee: bigint;
  currency: string;
};

export type LicensePermissionsStruct = {
  hasLicense: boolean;
  commercialUse: boolean;
  derivativesAllowed: boolean;
  minRevShare: BigNumberish;
};

export type LicensePermissionsStructOutput = [
  hasLicense: boolean,
  commercialUse: boolean,
  derivativesAllowed: boolean,
  minRevShare: bigint
] & {
  hasLicense: boolean;
  commercialUse: boolean;
  derivativesAllowed: boolean;
  minRevShare: bigint;
};

export interface LicenseViewerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LICENSE_REGISTRY"
      | "PIL_TEMPLATE"
      | "getIPLicenses"
      | "getLicensePermissions"
      | "getLicenseText"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LICENSE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIPLicenses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLicensePermissions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLicenseText",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LICENSE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIPLicenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLicensePermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLicenseText",
    data: BytesLike
  ): Result;
}

export interface LicenseViewer extends BaseContract {
  connect(runner?: ContractRunner | null): LicenseViewer;
  waitForDeployment(): Promise<this>;

  interface: LicenseViewerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LICENSE_REGISTRY: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  getIPLicenses: TypedContractMethod<
    [ipId: AddressLike],
    [LicenseDataStructOutput[]],
    "view"
  >;

  getLicensePermissions: TypedContractMethod<
    [ipId: AddressLike],
    [LicensePermissionsStructOutput],
    "view"
  >;

  getLicenseText: TypedContractMethod<
    [ipId: AddressLike, index: BigNumberish],
    [[string, string] & { licenseURI: string; summary: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LICENSE_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIPLicenses"
  ): TypedContractMethod<
    [ipId: AddressLike],
    [LicenseDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLicensePermissions"
  ): TypedContractMethod<
    [ipId: AddressLike],
    [LicensePermissionsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLicenseText"
  ): TypedContractMethod<
    [ipId: AddressLike, index: BigNumberish],
    [[string, string] & { licenseURI: string; summary: string }],
    "view"
  >;

  filters: {};
}
