/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PILTermsStruct = {
  transferable: boolean;
  royaltyPolicy: AddressLike;
  defaultMintingFee: BigNumberish;
  expiration: BigNumberish;
  commercialUse: boolean;
  commercialAttribution: boolean;
  commercializerChecker: AddressLike;
  commercializerCheckerData: BytesLike;
  commercialRevShare: BigNumberish;
  commercialRevCeiling: BigNumberish;
  derivativesAllowed: boolean;
  derivativesAttribution: boolean;
  derivativesApproval: boolean;
  derivativesReciprocal: boolean;
  derivativeRevCeiling: BigNumberish;
  currency: AddressLike;
  uri: string;
};

export type PILTermsStructOutput = [
  transferable: boolean,
  royaltyPolicy: string,
  defaultMintingFee: bigint,
  expiration: bigint,
  commercialUse: boolean,
  commercialAttribution: boolean,
  commercializerChecker: string,
  commercializerCheckerData: string,
  commercialRevShare: bigint,
  commercialRevCeiling: bigint,
  derivativesAllowed: boolean,
  derivativesAttribution: boolean,
  derivativesApproval: boolean,
  derivativesReciprocal: boolean,
  derivativeRevCeiling: bigint,
  currency: string,
  uri: string
] & {
  transferable: boolean;
  royaltyPolicy: string;
  defaultMintingFee: bigint;
  expiration: bigint;
  commercialUse: boolean;
  commercialAttribution: boolean;
  commercializerChecker: string;
  commercializerCheckerData: string;
  commercialRevShare: bigint;
  commercialRevCeiling: bigint;
  derivativesAllowed: boolean;
  derivativesAttribution: boolean;
  derivativesApproval: boolean;
  derivativesReciprocal: boolean;
  derivativeRevCeiling: bigint;
  currency: string;
  uri: string;
};

export interface LicenseTermsManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MERC20"
      | "PIL_TEMPLATE"
      | "ROYALTY_POLICY_LAP"
      | "getLicenseTermsId"
      | "registerCommercialRemixTerms"
      | "registerCommercialUseTerms"
      | "registerCustomTerms"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LicenseTermsRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "MERC20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_POLICY_LAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLicenseTermsId",
    values: [PILTermsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCommercialRemixTerms",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCommercialUseTerms",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCustomTerms",
    values: [PILTermsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "MERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_POLICY_LAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLicenseTermsId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCommercialRemixTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCommercialUseTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCustomTerms",
    data: BytesLike
  ): Result;
}

export namespace LicenseTermsRegisteredEvent {
  export type InputTuple = [
    licenseTermsId: BigNumberish,
    registrar: AddressLike
  ];
  export type OutputTuple = [licenseTermsId: bigint, registrar: string];
  export interface OutputObject {
    licenseTermsId: bigint;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LicenseTermsManager extends BaseContract {
  connect(runner?: ContractRunner | null): LicenseTermsManager;
  waitForDeployment(): Promise<this>;

  interface: LicenseTermsManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MERC20: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  ROYALTY_POLICY_LAP: TypedContractMethod<[], [string], "view">;

  getLicenseTermsId: TypedContractMethod<
    [pilTerms: PILTermsStruct],
    [bigint],
    "view"
  >;

  registerCommercialRemixTerms: TypedContractMethod<
    [mintingFee: BigNumberish, commercialRevShare: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  registerCommercialUseTerms: TypedContractMethod<
    [mintingFee: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  registerCustomTerms: TypedContractMethod<
    [pilTerms: PILTermsStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MERC20"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_POLICY_LAP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLicenseTermsId"
  ): TypedContractMethod<[pilTerms: PILTermsStruct], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerCommercialRemixTerms"
  ): TypedContractMethod<
    [mintingFee: BigNumberish, commercialRevShare: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCommercialUseTerms"
  ): TypedContractMethod<[mintingFee: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "registerCustomTerms"
  ): TypedContractMethod<[pilTerms: PILTermsStruct], [bigint], "nonpayable">;

  getEvent(
    key: "LicenseTermsRegistered"
  ): TypedContractEvent<
    LicenseTermsRegisteredEvent.InputTuple,
    LicenseTermsRegisteredEvent.OutputTuple,
    LicenseTermsRegisteredEvent.OutputObject
  >;

  filters: {
    "LicenseTermsRegistered(uint256,address)": TypedContractEvent<
      LicenseTermsRegisteredEvent.InputTuple,
      LicenseTermsRegisteredEvent.OutputTuple,
      LicenseTermsRegisteredEvent.OutputObject
    >;
    LicenseTermsRegistered: TypedContractEvent<
      LicenseTermsRegisteredEvent.InputTuple,
      LicenseTermsRegisteredEvent.OutputTuple,
      LicenseTermsRegisteredEvent.OutputObject
    >;
  };
}
