/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LicenseTokenManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LICENSE_TOKEN"
      | "LICENSING_MODULE"
      | "PIL_TEMPLATE"
      | "isTokenOwner"
      | "mintLicenseTokens"
      | "ownerOf"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LicenseTokensMinted"): EventFragment;

  encodeFunctionData(
    functionFragment: "LICENSE_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenOwner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintLicenseTokens",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LICENSE_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintLicenseTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
}

export namespace LicenseTokensMintedEvent {
  export type InputTuple = [
    licensorIpId: AddressLike,
    licenseTermsId: BigNumberish,
    startTokenId: BigNumberish,
    amount: BigNumberish,
    receiver: AddressLike
  ];
  export type OutputTuple = [
    licensorIpId: string,
    licenseTermsId: bigint,
    startTokenId: bigint,
    amount: bigint,
    receiver: string
  ];
  export interface OutputObject {
    licensorIpId: string;
    licenseTermsId: bigint;
    startTokenId: bigint;
    amount: bigint;
    receiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LicenseTokenManager extends BaseContract {
  connect(runner?: ContractRunner | null): LicenseTokenManager;
  waitForDeployment(): Promise<this>;

  interface: LicenseTokenManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LICENSE_TOKEN: TypedContractMethod<[], [string], "view">;

  LICENSING_MODULE: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  isTokenOwner: TypedContractMethod<
    [tokenId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  mintLicenseTokens: TypedContractMethod<
    [
      licensorIpId: AddressLike,
      licenseTermsId: BigNumberish,
      amount: BigNumberish,
      receiver: AddressLike,
      maxMintingFee: BigNumberish,
      maxRevenueShare: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LICENSE_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isTokenOwner"
  ): TypedContractMethod<
    [tokenId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintLicenseTokens"
  ): TypedContractMethod<
    [
      licensorIpId: AddressLike,
      licenseTermsId: BigNumberish,
      amount: BigNumberish,
      receiver: AddressLike,
      maxMintingFee: BigNumberish,
      maxRevenueShare: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getEvent(
    key: "LicenseTokensMinted"
  ): TypedContractEvent<
    LicenseTokensMintedEvent.InputTuple,
    LicenseTokensMintedEvent.OutputTuple,
    LicenseTokensMintedEvent.OutputObject
  >;

  filters: {
    "LicenseTokensMinted(address,uint256,uint256,uint256,address)": TypedContractEvent<
      LicenseTokensMintedEvent.InputTuple,
      LicenseTokensMintedEvent.OutputTuple,
      LicenseTokensMintedEvent.OutputObject
    >;
    LicenseTokensMinted: TypedContractEvent<
      LicenseTokensMintedEvent.InputTuple,
      LicenseTokensMintedEvent.OutputTuple,
      LicenseTokensMintedEvent.OutputObject
    >;
  };
}
