/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RoyaltyManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ROYALTY_MODULE"
      | "ROYALTY_POLICY_LAP"
      | "ROYALTY_WORKFLOWS"
      | "approveRoyaltyModule"
      | "claimAllRevenue"
      | "getIpRoyaltyVault"
      | "payRoyalty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RevenueClaimed" | "RoyaltyPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ROYALTY_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_POLICY_LAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_WORKFLOWS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveRoyaltyModule",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllRevenue",
    values: [AddressLike, AddressLike, AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getIpRoyaltyVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payRoyalty",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ROYALTY_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_POLICY_LAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_WORKFLOWS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRoyaltyModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIpRoyaltyVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payRoyalty", data: BytesLike): Result;
}

export namespace RevenueClaimedEvent {
  export type InputTuple = [
    ancestorIpId: AddressLike,
    claimer: AddressLike,
    amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    ancestorIpId: string,
    claimer: string,
    amounts: bigint[]
  ];
  export interface OutputObject {
    ancestorIpId: string;
    claimer: string;
    amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoyaltyPaidEvent {
  export type InputTuple = [
    ipId: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [ipId: string, token: string, amount: bigint];
  export interface OutputObject {
    ipId: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RoyaltyManager extends BaseContract {
  connect(runner?: ContractRunner | null): RoyaltyManager;
  waitForDeployment(): Promise<this>;

  interface: RoyaltyManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ROYALTY_MODULE: TypedContractMethod<[], [string], "view">;

  ROYALTY_POLICY_LAP: TypedContractMethod<[], [string], "view">;

  ROYALTY_WORKFLOWS: TypedContractMethod<[], [string], "view">;

  approveRoyaltyModule: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimAllRevenue: TypedContractMethod<
    [
      ancestorIpId: AddressLike,
      claimer: AddressLike,
      childIpIds: AddressLike[],
      currencyTokens: AddressLike[]
    ],
    [bigint[]],
    "nonpayable"
  >;

  getIpRoyaltyVault: TypedContractMethod<[ipId: AddressLike], [string], "view">;

  payRoyalty: TypedContractMethod<
    [ipId: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ROYALTY_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_POLICY_LAP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_WORKFLOWS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveRoyaltyModule"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimAllRevenue"
  ): TypedContractMethod<
    [
      ancestorIpId: AddressLike,
      claimer: AddressLike,
      childIpIds: AddressLike[],
      currencyTokens: AddressLike[]
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIpRoyaltyVault"
  ): TypedContractMethod<[ipId: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "payRoyalty"
  ): TypedContractMethod<
    [ipId: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RevenueClaimed"
  ): TypedContractEvent<
    RevenueClaimedEvent.InputTuple,
    RevenueClaimedEvent.OutputTuple,
    RevenueClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RoyaltyPaid"
  ): TypedContractEvent<
    RoyaltyPaidEvent.InputTuple,
    RoyaltyPaidEvent.OutputTuple,
    RoyaltyPaidEvent.OutputObject
  >;

  filters: {
    "RevenueClaimed(address,address,uint256[])": TypedContractEvent<
      RevenueClaimedEvent.InputTuple,
      RevenueClaimedEvent.OutputTuple,
      RevenueClaimedEvent.OutputObject
    >;
    RevenueClaimed: TypedContractEvent<
      RevenueClaimedEvent.InputTuple,
      RevenueClaimedEvent.OutputTuple,
      RevenueClaimedEvent.OutputObject
    >;

    "RoyaltyPaid(address,address,uint256)": TypedContractEvent<
      RoyaltyPaidEvent.InputTuple,
      RoyaltyPaidEvent.OutputTuple,
      RoyaltyPaidEvent.OutputObject
    >;
    RoyaltyPaid: TypedContractEvent<
      RoyaltyPaidEvent.InputTuple,
      RoyaltyPaidEvent.OutputTuple,
      RoyaltyPaidEvent.OutputObject
    >;
  };
}
