/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StoryProtocolGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "IP_ASSET_REGISTRY"
      | "LICENSING_MODULE"
      | "MERC20"
      | "PIL_TEMPLATE"
      | "ROYALTY_POLICY_LAP"
      | "SIMPLE_NFT"
      | "batchCreateIPAssets"
      | "createDerivativeIP"
      | "createIPAssetWithLicense"
      | "onERC721Received"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DerivativeCreated"
      | "IPAssetCreated"
      | "LicenseTermsAttached"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "IP_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LICENSING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MERC20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PIL_TEMPLATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_POLICY_LAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIMPLE_NFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchCreateIPAssets",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDerivativeIP",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createIPAssetWithLicense",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IP_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LICENSING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PIL_TEMPLATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_POLICY_LAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SIMPLE_NFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchCreateIPAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDerivativeIP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIPAssetWithLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
}

export namespace DerivativeCreatedEvent {
  export type InputTuple = [
    childIpId: AddressLike,
    parentIpId: AddressLike,
    licenseTokenIds: BigNumberish[]
  ];
  export type OutputTuple = [
    childIpId: string,
    parentIpId: string,
    licenseTokenIds: bigint[]
  ];
  export interface OutputObject {
    childIpId: string;
    parentIpId: string;
    licenseTokenIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IPAssetCreatedEvent {
  export type InputTuple = [
    ipId: AddressLike,
    tokenId: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [ipId: string, tokenId: bigint, owner: string];
  export interface OutputObject {
    ipId: string;
    tokenId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseTermsAttachedEvent {
  export type InputTuple = [ipId: AddressLike, licenseTermsId: BigNumberish];
  export type OutputTuple = [ipId: string, licenseTermsId: bigint];
  export interface OutputObject {
    ipId: string;
    licenseTermsId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StoryProtocolGateway extends BaseContract {
  connect(runner?: ContractRunner | null): StoryProtocolGateway;
  waitForDeployment(): Promise<this>;

  interface: StoryProtocolGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IP_ASSET_REGISTRY: TypedContractMethod<[], [string], "view">;

  LICENSING_MODULE: TypedContractMethod<[], [string], "view">;

  MERC20: TypedContractMethod<[], [string], "view">;

  PIL_TEMPLATE: TypedContractMethod<[], [string], "view">;

  ROYALTY_POLICY_LAP: TypedContractMethod<[], [string], "view">;

  SIMPLE_NFT: TypedContractMethod<[], [string], "view">;

  batchCreateIPAssets: TypedContractMethod<
    [receivers: AddressLike[], commercialRevShare: BigNumberish],
    [
      [bigint[], string[], bigint] & {
        tokenIds: bigint[];
        ipIds: string[];
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;

  createDerivativeIP: TypedContractMethod<
    [
      parentIpId: AddressLike,
      licenseTermsId: BigNumberish,
      receiver: AddressLike
    ],
    [[bigint, string] & { childTokenId: bigint; childIpId: string }],
    "nonpayable"
  >;

  createIPAssetWithLicense: TypedContractMethod<
    [receiver: AddressLike, commercialRevShare: BigNumberish],
    [
      [bigint, string, bigint] & {
        tokenId: bigint;
        ipId: string;
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IP_ASSET_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LICENSING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MERC20"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIL_TEMPLATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_POLICY_LAP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SIMPLE_NFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchCreateIPAssets"
  ): TypedContractMethod<
    [receivers: AddressLike[], commercialRevShare: BigNumberish],
    [
      [bigint[], string[], bigint] & {
        tokenIds: bigint[];
        ipIds: string[];
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDerivativeIP"
  ): TypedContractMethod<
    [
      parentIpId: AddressLike,
      licenseTermsId: BigNumberish,
      receiver: AddressLike
    ],
    [[bigint, string] & { childTokenId: bigint; childIpId: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIPAssetWithLicense"
  ): TypedContractMethod<
    [receiver: AddressLike, commercialRevShare: BigNumberish],
    [
      [bigint, string, bigint] & {
        tokenId: bigint;
        ipId: string;
        licenseTermsId: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "DerivativeCreated"
  ): TypedContractEvent<
    DerivativeCreatedEvent.InputTuple,
    DerivativeCreatedEvent.OutputTuple,
    DerivativeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IPAssetCreated"
  ): TypedContractEvent<
    IPAssetCreatedEvent.InputTuple,
    IPAssetCreatedEvent.OutputTuple,
    IPAssetCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseTermsAttached"
  ): TypedContractEvent<
    LicenseTermsAttachedEvent.InputTuple,
    LicenseTermsAttachedEvent.OutputTuple,
    LicenseTermsAttachedEvent.OutputObject
  >;

  filters: {
    "DerivativeCreated(address,address,uint256[])": TypedContractEvent<
      DerivativeCreatedEvent.InputTuple,
      DerivativeCreatedEvent.OutputTuple,
      DerivativeCreatedEvent.OutputObject
    >;
    DerivativeCreated: TypedContractEvent<
      DerivativeCreatedEvent.InputTuple,
      DerivativeCreatedEvent.OutputTuple,
      DerivativeCreatedEvent.OutputObject
    >;

    "IPAssetCreated(address,uint256,address)": TypedContractEvent<
      IPAssetCreatedEvent.InputTuple,
      IPAssetCreatedEvent.OutputTuple,
      IPAssetCreatedEvent.OutputObject
    >;
    IPAssetCreated: TypedContractEvent<
      IPAssetCreatedEvent.InputTuple,
      IPAssetCreatedEvent.OutputTuple,
      IPAssetCreatedEvent.OutputObject
    >;

    "LicenseTermsAttached(address,uint256)": TypedContractEvent<
      LicenseTermsAttachedEvent.InputTuple,
      LicenseTermsAttachedEvent.OutputTuple,
      LicenseTermsAttachedEvent.OutputObject
    >;
    LicenseTermsAttached: TypedContractEvent<
      LicenseTermsAttachedEvent.InputTuple,
      LicenseTermsAttachedEvent.OutputTuple,
      LicenseTermsAttachedEvent.OutputObject
    >;
  };
}
