/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7572,
  IERC7572Interface,
} from "../../../../../../@storyprotocol/periphery/contracts/interfaces/story-nft/IERC7572";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "ContractURIUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "contractURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC7572__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7572Interface {
    return new Interface(_abi) as IERC7572Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC7572 {
    return new Contract(address, _abi, runner) as unknown as IERC7572;
  }
}
