/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as modules from "./modules";
export type { modules };
import type * as registries from "./registries";
export type { registries };
export type { ILicenseToken } from "./ILicenseToken";
