/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storyNft from "./story-nft";
export type { storyNft };
import type * as workflows from "./workflows";
export type { workflows };
export type { ISPGNFT } from "./ISPGNFT";
