/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721Holder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Holder__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "IAccessController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessController__factory>;
    getContractFactory(
      name: "ILicenseToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILicenseToken__factory>;
    getContractFactory(
      name: "IModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IModule__factory>;
    getContractFactory(
      name: "ILicenseTemplate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILicenseTemplate__factory>;
    getContractFactory(
      name: "ILicensingModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILicensingModule__factory>;
    getContractFactory(
      name: "IPILicenseTemplate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPILicenseTemplate__factory>;
    getContractFactory(
      name: "IRoyaltyModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRoyaltyModule__factory>;
    getContractFactory(
      name: "IIPAccountRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIPAccountRegistry__factory>;
    getContractFactory(
      name: "IIPAssetRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIPAssetRegistry__factory>;
    getContractFactory(
      name: "ILicenseRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILicenseRegistry__factory>;
    getContractFactory(
      name: "AccessPermission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessPermission__factory>;
    getContractFactory(
      name: "PILFlavors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PILFlavors__factory>;
    getContractFactory(
      name: "ISPGNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISPGNFT__factory>;
    getContractFactory(
      name: "IERC7572",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC7572__factory>;
    getContractFactory(
      name: "IRegistrationWorkflows",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRegistrationWorkflows__factory>;
    getContractFactory(
      name: "IRoyaltyWorkflows",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRoyaltyWorkflows__factory>;
    getContractFactory(
      name: "DerivativeManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DerivativeManager__factory>;
    getContractFactory(
      name: "Example",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Example__factory>;
    getContractFactory(
      name: "IPAccountManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPAccountManager__factory>;
    getContractFactory(
      name: "IPARegistrar",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPARegistrar__factory>;
    getContractFactory(
      name: "IPCreator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPCreator__factory>;
    getContractFactory(
      name: "IPMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPMarketplace__factory>;
    getContractFactory(
      name: "IPToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPToken__factory>;
    getContractFactory(
      name: "LicenseAttacher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LicenseAttacher__factory>;
    getContractFactory(
      name: "LicenseTermsManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LicenseTermsManager__factory>;
    getContractFactory(
      name: "LicenseTokenManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LicenseTokenManager__factory>;
    getContractFactory(
      name: "LicenseViewer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LicenseViewer__factory>;
    getContractFactory(
      name: "SimpleNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleNFT__factory>;
    getContractFactory(
      name: "RoyaltyManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RoyaltyManager__factory>;
    getContractFactory(
      name: "StoryProtocolGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StoryProtocolGateway__factory>;

    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Enumerable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Enumerable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC721Holder",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Holder>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "IAccessController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessController>;
    getContractAt(
      name: "ILicenseToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILicenseToken>;
    getContractAt(
      name: "IModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IModule>;
    getContractAt(
      name: "ILicenseTemplate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILicenseTemplate>;
    getContractAt(
      name: "ILicensingModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILicensingModule>;
    getContractAt(
      name: "IPILicenseTemplate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPILicenseTemplate>;
    getContractAt(
      name: "IRoyaltyModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRoyaltyModule>;
    getContractAt(
      name: "IIPAccountRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIPAccountRegistry>;
    getContractAt(
      name: "IIPAssetRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIPAssetRegistry>;
    getContractAt(
      name: "ILicenseRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILicenseRegistry>;
    getContractAt(
      name: "AccessPermission",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessPermission>;
    getContractAt(
      name: "PILFlavors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PILFlavors>;
    getContractAt(
      name: "ISPGNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISPGNFT>;
    getContractAt(
      name: "IERC7572",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC7572>;
    getContractAt(
      name: "IRegistrationWorkflows",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRegistrationWorkflows>;
    getContractAt(
      name: "IRoyaltyWorkflows",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRoyaltyWorkflows>;
    getContractAt(
      name: "DerivativeManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DerivativeManager>;
    getContractAt(
      name: "Example",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Example>;
    getContractAt(
      name: "IPAccountManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPAccountManager>;
    getContractAt(
      name: "IPARegistrar",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPARegistrar>;
    getContractAt(
      name: "IPCreator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPCreator>;
    getContractAt(
      name: "IPMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPMarketplace>;
    getContractAt(
      name: "IPToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPToken>;
    getContractAt(
      name: "LicenseAttacher",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LicenseAttacher>;
    getContractAt(
      name: "LicenseTermsManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LicenseTermsManager>;
    getContractAt(
      name: "LicenseTokenManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LicenseTokenManager>;
    getContractAt(
      name: "LicenseViewer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LicenseViewer>;
    getContractAt(
      name: "SimpleNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleNFT>;
    getContractAt(
      name: "RoyaltyManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RoyaltyManager>;
    getContractAt(
      name: "StoryProtocolGateway",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StoryProtocolGateway>;

    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Enumerable>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "ERC721Holder",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721Holder>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "IAccessController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessController>;
    deployContract(
      name: "ILicenseToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicenseToken>;
    deployContract(
      name: "IModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModule>;
    deployContract(
      name: "ILicenseTemplate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicenseTemplate>;
    deployContract(
      name: "ILicensingModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicensingModule>;
    deployContract(
      name: "IPILicenseTemplate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPILicenseTemplate>;
    deployContract(
      name: "IRoyaltyModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRoyaltyModule>;
    deployContract(
      name: "IIPAccountRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIPAccountRegistry>;
    deployContract(
      name: "IIPAssetRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIPAssetRegistry>;
    deployContract(
      name: "ILicenseRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicenseRegistry>;
    deployContract(
      name: "AccessPermission",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessPermission>;
    deployContract(
      name: "PILFlavors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PILFlavors>;
    deployContract(
      name: "ISPGNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISPGNFT>;
    deployContract(
      name: "IERC7572",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7572>;
    deployContract(
      name: "IRegistrationWorkflows",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegistrationWorkflows>;
    deployContract(
      name: "IRoyaltyWorkflows",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRoyaltyWorkflows>;
    deployContract(
      name: "DerivativeManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DerivativeManager>;
    deployContract(
      name: "Example",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Example>;
    deployContract(
      name: "IPAccountManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPAccountManager>;
    deployContract(
      name: "IPARegistrar",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPARegistrar>;
    deployContract(
      name: "IPCreator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPCreator>;
    deployContract(
      name: "IPMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPMarketplace>;
    deployContract(
      name: "IPToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPToken>;
    deployContract(
      name: "LicenseAttacher",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseAttacher>;
    deployContract(
      name: "LicenseTermsManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseTermsManager>;
    deployContract(
      name: "LicenseTokenManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseTokenManager>;
    deployContract(
      name: "LicenseViewer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseViewer>;
    deployContract(
      name: "SimpleNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleNFT>;
    deployContract(
      name: "RoyaltyManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RoyaltyManager>;
    deployContract(
      name: "StoryProtocolGateway",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StoryProtocolGateway>;

    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Enumerable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Enumerable>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "ERC721Holder",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721Holder>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "IAccessController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessController>;
    deployContract(
      name: "ILicenseToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicenseToken>;
    deployContract(
      name: "IModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModule>;
    deployContract(
      name: "ILicenseTemplate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicenseTemplate>;
    deployContract(
      name: "ILicensingModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicensingModule>;
    deployContract(
      name: "IPILicenseTemplate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPILicenseTemplate>;
    deployContract(
      name: "IRoyaltyModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRoyaltyModule>;
    deployContract(
      name: "IIPAccountRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIPAccountRegistry>;
    deployContract(
      name: "IIPAssetRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIPAssetRegistry>;
    deployContract(
      name: "ILicenseRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILicenseRegistry>;
    deployContract(
      name: "AccessPermission",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessPermission>;
    deployContract(
      name: "PILFlavors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PILFlavors>;
    deployContract(
      name: "ISPGNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISPGNFT>;
    deployContract(
      name: "IERC7572",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7572>;
    deployContract(
      name: "IRegistrationWorkflows",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegistrationWorkflows>;
    deployContract(
      name: "IRoyaltyWorkflows",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRoyaltyWorkflows>;
    deployContract(
      name: "DerivativeManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DerivativeManager>;
    deployContract(
      name: "Example",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Example>;
    deployContract(
      name: "IPAccountManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPAccountManager>;
    deployContract(
      name: "IPARegistrar",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPARegistrar>;
    deployContract(
      name: "IPCreator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPCreator>;
    deployContract(
      name: "IPMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPMarketplace>;
    deployContract(
      name: "IPToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPToken>;
    deployContract(
      name: "LicenseAttacher",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseAttacher>;
    deployContract(
      name: "LicenseTermsManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseTermsManager>;
    deployContract(
      name: "LicenseTokenManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseTokenManager>;
    deployContract(
      name: "LicenseViewer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LicenseViewer>;
    deployContract(
      name: "SimpleNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleNFT>;
    deployContract(
      name: "RoyaltyManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RoyaltyManager>;
    deployContract(
      name: "StoryProtocolGateway",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StoryProtocolGateway>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
